name: Deploy Terraform After Testing

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-west-2'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.x
    
      - name: Set AWS region for testing
        run: |
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python lambda-function/test_visit_counter.py

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: test  # Wait for the 'test' job to complete

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Set AWS region for deployment
        run: |
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV

      - name: Terraform Apply
        run: terraform apply --auto-approve
